apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapi3
  template:
    metadata:
      labels:
        app: testapi3
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: testapi3container
        image: saurabhtestacr.azurecr.io/testapi3:v8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
